// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_info_base.proto

#include "message_info_base.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace raybo {
PROTOBUF_CONSTEXPR MessageInfoBase::MessageInfoBase(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.content_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ver_)*/0u
  , /*decltype(_impl_.message_id_)*/0u
  , /*decltype(_impl_.publisher_id_)*/0u
  , /*decltype(_impl_.publish_time_)*/0u} {}
struct MessageInfoBaseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessageInfoBaseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageInfoBaseDefaultTypeInternal() {}
  union {
    MessageInfoBase _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageInfoBaseDefaultTypeInternal _MessageInfoBase_default_instance_;
}  // namespace raybo
static ::_pb::Metadata file_level_metadata_message_5finfo_5fbase_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_message_5finfo_5fbase_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_message_5finfo_5fbase_2eproto = nullptr;

const uint32_t TableStruct_message_5finfo_5fbase_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::raybo::MessageInfoBase, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::raybo::MessageInfoBase, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::raybo::MessageInfoBase, _impl_.ver_),
  PROTOBUF_FIELD_OFFSET(::raybo::MessageInfoBase, _impl_.message_id_),
  PROTOBUF_FIELD_OFFSET(::raybo::MessageInfoBase, _impl_.publisher_id_),
  PROTOBUF_FIELD_OFFSET(::raybo::MessageInfoBase, _impl_.publish_time_),
  PROTOBUF_FIELD_OFFSET(::raybo::MessageInfoBase, _impl_.content_),
  1,
  2,
  3,
  4,
  0,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 11, -1, sizeof(::raybo::MessageInfoBase)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::raybo::_MessageInfoBase_default_instance_._instance,
};

const char descriptor_table_protodef_message_5finfo_5fbase_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027message_info_base.proto\022\005raybo\"\315\001\n\017Mes"
  "sageInfoBase\022\020\n\003ver\030\001 \001(\rH\000\210\001\001\022\027\n\nmessag"
  "e_id\030\002 \001(\rH\001\210\001\001\022\031\n\014publisher_id\030\003 \001(\rH\002\210"
  "\001\001\022\031\n\014publish_time\030\004 \001(\rH\003\210\001\001\022\024\n\007content"
  "\030\005 \001(\tH\004\210\001\001B\006\n\004_verB\r\n\013_message_idB\017\n\r_p"
  "ublisher_idB\017\n\r_publish_timeB\n\n\010_content"
  "b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_message_5finfo_5fbase_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_message_5finfo_5fbase_2eproto = {
    false, false, 248, descriptor_table_protodef_message_5finfo_5fbase_2eproto,
    "message_info_base.proto",
    &descriptor_table_message_5finfo_5fbase_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_message_5finfo_5fbase_2eproto::offsets,
    file_level_metadata_message_5finfo_5fbase_2eproto, file_level_enum_descriptors_message_5finfo_5fbase_2eproto,
    file_level_service_descriptors_message_5finfo_5fbase_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_message_5finfo_5fbase_2eproto_getter() {
  return &descriptor_table_message_5finfo_5fbase_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_message_5finfo_5fbase_2eproto(&descriptor_table_message_5finfo_5fbase_2eproto);
namespace raybo {

// ===================================================================

class MessageInfoBase::_Internal {
 public:
  using HasBits = decltype(std::declval<MessageInfoBase>()._impl_._has_bits_);
  static void set_has_ver(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_message_id(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_publisher_id(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_publish_time(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_content(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

MessageInfoBase::MessageInfoBase(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:raybo.MessageInfoBase)
}
MessageInfoBase::MessageInfoBase(const MessageInfoBase& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.content_){}
    , decltype(_impl_.ver_){}
    , decltype(_impl_.message_id_){}
    , decltype(_impl_.publisher_id_){}
    , decltype(_impl_.publish_time_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_content()) {
    _impl_.content_.Set(from._internal_content(), 
      GetArenaForAllocation());
  }
  ::memcpy(&_impl_.ver_, &from._impl_.ver_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.publish_time_) -
    reinterpret_cast<char*>(&_impl_.ver_)) + sizeof(_impl_.publish_time_));
  // @@protoc_insertion_point(copy_constructor:raybo.MessageInfoBase)
}

inline void MessageInfoBase::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.content_){}
    , decltype(_impl_.ver_){0u}
    , decltype(_impl_.message_id_){0u}
    , decltype(_impl_.publisher_id_){0u}
    , decltype(_impl_.publish_time_){0u}
  };
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

MessageInfoBase::~MessageInfoBase() {
  // @@protoc_insertion_point(destructor:raybo.MessageInfoBase)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MessageInfoBase::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.content_.Destroy();
}

void MessageInfoBase::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MessageInfoBase::Clear() {
// @@protoc_insertion_point(message_clear_start:raybo.MessageInfoBase)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.content_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x0000001eu) {
    ::memset(&_impl_.ver_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.publish_time_) -
        reinterpret_cast<char*>(&_impl_.ver_)) + sizeof(_impl_.publish_time_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MessageInfoBase::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 ver = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_ver(&has_bits);
          _impl_.ver_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 message_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_message_id(&has_bits);
          _impl_.message_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 publisher_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_publisher_id(&has_bits);
          _impl_.publisher_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 publish_time = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _Internal::set_has_publish_time(&has_bits);
          _impl_.publish_time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string content = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_content();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "raybo.MessageInfoBase.content"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MessageInfoBase::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:raybo.MessageInfoBase)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional uint32 ver = 1;
  if (_internal_has_ver()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_ver(), target);
  }

  // optional uint32 message_id = 2;
  if (_internal_has_message_id()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_message_id(), target);
  }

  // optional uint32 publisher_id = 3;
  if (_internal_has_publisher_id()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_publisher_id(), target);
  }

  // optional uint32 publish_time = 4;
  if (_internal_has_publish_time()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_publish_time(), target);
  }

  // optional string content = 5;
  if (_internal_has_content()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_content().data(), static_cast<int>(this->_internal_content().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "raybo.MessageInfoBase.content");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_content(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:raybo.MessageInfoBase)
  return target;
}

size_t MessageInfoBase::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:raybo.MessageInfoBase)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    // optional string content = 5;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_content());
    }

    // optional uint32 ver = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_ver());
    }

    // optional uint32 message_id = 2;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_message_id());
    }

    // optional uint32 publisher_id = 3;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_publisher_id());
    }

    // optional uint32 publish_time = 4;
    if (cached_has_bits & 0x00000010u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_publish_time());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MessageInfoBase::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MessageInfoBase::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MessageInfoBase::GetClassData() const { return &_class_data_; }

void MessageInfoBase::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<MessageInfoBase *>(to)->MergeFrom(
      static_cast<const MessageInfoBase &>(from));
}


void MessageInfoBase::MergeFrom(const MessageInfoBase& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:raybo.MessageInfoBase)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_content(from._internal_content());
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.ver_ = from._impl_.ver_;
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.message_id_ = from._impl_.message_id_;
    }
    if (cached_has_bits & 0x00000008u) {
      _impl_.publisher_id_ = from._impl_.publisher_id_;
    }
    if (cached_has_bits & 0x00000010u) {
      _impl_.publish_time_ = from._impl_.publish_time_;
    }
    _impl_._has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MessageInfoBase::CopyFrom(const MessageInfoBase& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:raybo.MessageInfoBase)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageInfoBase::IsInitialized() const {
  return true;
}

void MessageInfoBase::InternalSwap(MessageInfoBase* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.content_, lhs_arena,
      &other->_impl_.content_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MessageInfoBase, _impl_.publish_time_)
      + sizeof(MessageInfoBase::_impl_.publish_time_)
      - PROTOBUF_FIELD_OFFSET(MessageInfoBase, _impl_.ver_)>(
          reinterpret_cast<char*>(&_impl_.ver_),
          reinterpret_cast<char*>(&other->_impl_.ver_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MessageInfoBase::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_message_5finfo_5fbase_2eproto_getter, &descriptor_table_message_5finfo_5fbase_2eproto_once,
      file_level_metadata_message_5finfo_5fbase_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace raybo
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::raybo::MessageInfoBase*
Arena::CreateMaybeMessage< ::raybo::MessageInfoBase >(Arena* arena) {
  return Arena::CreateMessageInternal< ::raybo::MessageInfoBase >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
