// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: photo_info_base.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_photo_5finfo_5fbase_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_photo_5finfo_5fbase_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_photo_5finfo_5fbase_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_photo_5finfo_5fbase_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_photo_5finfo_5fbase_2eproto;
namespace raybo {
class PhotoInfoBase;
struct PhotoInfoBaseDefaultTypeInternal;
extern PhotoInfoBaseDefaultTypeInternal _PhotoInfoBase_default_instance_;
}  // namespace raybo
PROTOBUF_NAMESPACE_OPEN
template<> ::raybo::PhotoInfoBase* Arena::CreateMaybeMessage<::raybo::PhotoInfoBase>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace raybo {

// ===================================================================

class PhotoInfoBase final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raybo.PhotoInfoBase) */ {
 public:
  inline PhotoInfoBase() : PhotoInfoBase(nullptr) {}
  ~PhotoInfoBase() override;
  explicit PROTOBUF_CONSTEXPR PhotoInfoBase(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PhotoInfoBase(const PhotoInfoBase& from);
  PhotoInfoBase(PhotoInfoBase&& from) noexcept
    : PhotoInfoBase() {
    *this = ::std::move(from);
  }

  inline PhotoInfoBase& operator=(const PhotoInfoBase& from) {
    CopyFrom(from);
    return *this;
  }
  inline PhotoInfoBase& operator=(PhotoInfoBase&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PhotoInfoBase& default_instance() {
    return *internal_default_instance();
  }
  static inline const PhotoInfoBase* internal_default_instance() {
    return reinterpret_cast<const PhotoInfoBase*>(
               &_PhotoInfoBase_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PhotoInfoBase& a, PhotoInfoBase& b) {
    a.Swap(&b);
  }
  inline void Swap(PhotoInfoBase* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PhotoInfoBase* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PhotoInfoBase* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PhotoInfoBase>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PhotoInfoBase& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const PhotoInfoBase& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PhotoInfoBase* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raybo.PhotoInfoBase";
  }
  protected:
  explicit PhotoInfoBase(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVerFieldNumber = 1,
    kUserIdFieldNumber = 2,
    kLastPublisherFieldNumber = 3,
    kLastPublishTimeFieldNumber = 4,
    kLastPublishMessageIdFieldNumber = 5,
  };
  // optional uint32 ver = 1;
  bool has_ver() const;
  private:
  bool _internal_has_ver() const;
  public:
  void clear_ver();
  uint32_t ver() const;
  void set_ver(uint32_t value);
  private:
  uint32_t _internal_ver() const;
  void _internal_set_ver(uint32_t value);
  public:

  // optional uint32 user_id = 2;
  bool has_user_id() const;
  private:
  bool _internal_has_user_id() const;
  public:
  void clear_user_id();
  uint32_t user_id() const;
  void set_user_id(uint32_t value);
  private:
  uint32_t _internal_user_id() const;
  void _internal_set_user_id(uint32_t value);
  public:

  // optional uint32 last_publisher = 3;
  bool has_last_publisher() const;
  private:
  bool _internal_has_last_publisher() const;
  public:
  void clear_last_publisher();
  uint32_t last_publisher() const;
  void set_last_publisher(uint32_t value);
  private:
  uint32_t _internal_last_publisher() const;
  void _internal_set_last_publisher(uint32_t value);
  public:

  // optional uint32 last_publish_time = 4;
  bool has_last_publish_time() const;
  private:
  bool _internal_has_last_publish_time() const;
  public:
  void clear_last_publish_time();
  uint32_t last_publish_time() const;
  void set_last_publish_time(uint32_t value);
  private:
  uint32_t _internal_last_publish_time() const;
  void _internal_set_last_publish_time(uint32_t value);
  public:

  // optional uint32 last_publish_message_id = 5;
  bool has_last_publish_message_id() const;
  private:
  bool _internal_has_last_publish_message_id() const;
  public:
  void clear_last_publish_message_id();
  uint32_t last_publish_message_id() const;
  void set_last_publish_message_id(uint32_t value);
  private:
  uint32_t _internal_last_publish_message_id() const;
  void _internal_set_last_publish_message_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:raybo.PhotoInfoBase)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t ver_;
    uint32_t user_id_;
    uint32_t last_publisher_;
    uint32_t last_publish_time_;
    uint32_t last_publish_message_id_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_photo_5finfo_5fbase_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PhotoInfoBase

// optional uint32 ver = 1;
inline bool PhotoInfoBase::_internal_has_ver() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PhotoInfoBase::has_ver() const {
  return _internal_has_ver();
}
inline void PhotoInfoBase::clear_ver() {
  _impl_.ver_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t PhotoInfoBase::_internal_ver() const {
  return _impl_.ver_;
}
inline uint32_t PhotoInfoBase::ver() const {
  // @@protoc_insertion_point(field_get:raybo.PhotoInfoBase.ver)
  return _internal_ver();
}
inline void PhotoInfoBase::_internal_set_ver(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.ver_ = value;
}
inline void PhotoInfoBase::set_ver(uint32_t value) {
  _internal_set_ver(value);
  // @@protoc_insertion_point(field_set:raybo.PhotoInfoBase.ver)
}

// optional uint32 user_id = 2;
inline bool PhotoInfoBase::_internal_has_user_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool PhotoInfoBase::has_user_id() const {
  return _internal_has_user_id();
}
inline void PhotoInfoBase::clear_user_id() {
  _impl_.user_id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t PhotoInfoBase::_internal_user_id() const {
  return _impl_.user_id_;
}
inline uint32_t PhotoInfoBase::user_id() const {
  // @@protoc_insertion_point(field_get:raybo.PhotoInfoBase.user_id)
  return _internal_user_id();
}
inline void PhotoInfoBase::_internal_set_user_id(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.user_id_ = value;
}
inline void PhotoInfoBase::set_user_id(uint32_t value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:raybo.PhotoInfoBase.user_id)
}

// optional uint32 last_publisher = 3;
inline bool PhotoInfoBase::_internal_has_last_publisher() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool PhotoInfoBase::has_last_publisher() const {
  return _internal_has_last_publisher();
}
inline void PhotoInfoBase::clear_last_publisher() {
  _impl_.last_publisher_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline uint32_t PhotoInfoBase::_internal_last_publisher() const {
  return _impl_.last_publisher_;
}
inline uint32_t PhotoInfoBase::last_publisher() const {
  // @@protoc_insertion_point(field_get:raybo.PhotoInfoBase.last_publisher)
  return _internal_last_publisher();
}
inline void PhotoInfoBase::_internal_set_last_publisher(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.last_publisher_ = value;
}
inline void PhotoInfoBase::set_last_publisher(uint32_t value) {
  _internal_set_last_publisher(value);
  // @@protoc_insertion_point(field_set:raybo.PhotoInfoBase.last_publisher)
}

// optional uint32 last_publish_time = 4;
inline bool PhotoInfoBase::_internal_has_last_publish_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool PhotoInfoBase::has_last_publish_time() const {
  return _internal_has_last_publish_time();
}
inline void PhotoInfoBase::clear_last_publish_time() {
  _impl_.last_publish_time_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline uint32_t PhotoInfoBase::_internal_last_publish_time() const {
  return _impl_.last_publish_time_;
}
inline uint32_t PhotoInfoBase::last_publish_time() const {
  // @@protoc_insertion_point(field_get:raybo.PhotoInfoBase.last_publish_time)
  return _internal_last_publish_time();
}
inline void PhotoInfoBase::_internal_set_last_publish_time(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.last_publish_time_ = value;
}
inline void PhotoInfoBase::set_last_publish_time(uint32_t value) {
  _internal_set_last_publish_time(value);
  // @@protoc_insertion_point(field_set:raybo.PhotoInfoBase.last_publish_time)
}

// optional uint32 last_publish_message_id = 5;
inline bool PhotoInfoBase::_internal_has_last_publish_message_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool PhotoInfoBase::has_last_publish_message_id() const {
  return _internal_has_last_publish_message_id();
}
inline void PhotoInfoBase::clear_last_publish_message_id() {
  _impl_.last_publish_message_id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline uint32_t PhotoInfoBase::_internal_last_publish_message_id() const {
  return _impl_.last_publish_message_id_;
}
inline uint32_t PhotoInfoBase::last_publish_message_id() const {
  // @@protoc_insertion_point(field_get:raybo.PhotoInfoBase.last_publish_message_id)
  return _internal_last_publish_message_id();
}
inline void PhotoInfoBase::_internal_set_last_publish_message_id(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.last_publish_message_id_ = value;
}
inline void PhotoInfoBase::set_last_publish_message_id(uint32_t value) {
  _internal_set_last_publish_message_id(value);
  // @@protoc_insertion_point(field_set:raybo.PhotoInfoBase.last_publish_message_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace raybo

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_photo_5finfo_5fbase_2eproto
