// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: relation_info_base.proto

#include "relation_info_base.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace raybo {
PROTOBUF_CONSTEXPR RelationInfoBase::RelationInfoBase(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.friend_list_)*/{}
  , /*decltype(_impl_._friend_list_cached_byte_size_)*/{0}
  , /*decltype(_impl_.black_list_)*/{}
  , /*decltype(_impl_._black_list_cached_byte_size_)*/{0}
  , /*decltype(_impl_.ver_)*/0u
  , /*decltype(_impl_.user_id_)*/0u} {}
struct RelationInfoBaseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RelationInfoBaseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RelationInfoBaseDefaultTypeInternal() {}
  union {
    RelationInfoBase _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RelationInfoBaseDefaultTypeInternal _RelationInfoBase_default_instance_;
}  // namespace raybo
static ::_pb::Metadata file_level_metadata_relation_5finfo_5fbase_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_relation_5finfo_5fbase_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_relation_5finfo_5fbase_2eproto = nullptr;

const uint32_t TableStruct_relation_5finfo_5fbase_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::raybo::RelationInfoBase, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::raybo::RelationInfoBase, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::raybo::RelationInfoBase, _impl_.ver_),
  PROTOBUF_FIELD_OFFSET(::raybo::RelationInfoBase, _impl_.user_id_),
  PROTOBUF_FIELD_OFFSET(::raybo::RelationInfoBase, _impl_.friend_list_),
  PROTOBUF_FIELD_OFFSET(::raybo::RelationInfoBase, _impl_.black_list_),
  0,
  1,
  ~0u,
  ~0u,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 10, -1, sizeof(::raybo::RelationInfoBase)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::raybo::_RelationInfoBase_default_instance_._instance,
};

const char descriptor_table_protodef_relation_5finfo_5fbase_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030relation_info_base.proto\022\005raybo\"w\n\020Rel"
  "ationInfoBase\022\020\n\003ver\030\001 \001(\rH\000\210\001\001\022\024\n\007user_"
  "id\030\002 \001(\rH\001\210\001\001\022\023\n\013friend_list\030\003 \003(\r\022\022\n\nbl"
  "ack_list\030\004 \003(\rB\006\n\004_verB\n\n\010_user_idb\006prot"
  "o3"
  ;
static ::_pbi::once_flag descriptor_table_relation_5finfo_5fbase_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_relation_5finfo_5fbase_2eproto = {
    false, false, 162, descriptor_table_protodef_relation_5finfo_5fbase_2eproto,
    "relation_info_base.proto",
    &descriptor_table_relation_5finfo_5fbase_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_relation_5finfo_5fbase_2eproto::offsets,
    file_level_metadata_relation_5finfo_5fbase_2eproto, file_level_enum_descriptors_relation_5finfo_5fbase_2eproto,
    file_level_service_descriptors_relation_5finfo_5fbase_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_relation_5finfo_5fbase_2eproto_getter() {
  return &descriptor_table_relation_5finfo_5fbase_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_relation_5finfo_5fbase_2eproto(&descriptor_table_relation_5finfo_5fbase_2eproto);
namespace raybo {

// ===================================================================

class RelationInfoBase::_Internal {
 public:
  using HasBits = decltype(std::declval<RelationInfoBase>()._impl_._has_bits_);
  static void set_has_ver(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_user_id(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

RelationInfoBase::RelationInfoBase(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:raybo.RelationInfoBase)
}
RelationInfoBase::RelationInfoBase(const RelationInfoBase& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.friend_list_){from._impl_.friend_list_}
    , /*decltype(_impl_._friend_list_cached_byte_size_)*/{0}
    , decltype(_impl_.black_list_){from._impl_.black_list_}
    , /*decltype(_impl_._black_list_cached_byte_size_)*/{0}
    , decltype(_impl_.ver_){}
    , decltype(_impl_.user_id_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.ver_, &from._impl_.ver_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.user_id_) -
    reinterpret_cast<char*>(&_impl_.ver_)) + sizeof(_impl_.user_id_));
  // @@protoc_insertion_point(copy_constructor:raybo.RelationInfoBase)
}

inline void RelationInfoBase::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.friend_list_){arena}
    , /*decltype(_impl_._friend_list_cached_byte_size_)*/{0}
    , decltype(_impl_.black_list_){arena}
    , /*decltype(_impl_._black_list_cached_byte_size_)*/{0}
    , decltype(_impl_.ver_){0u}
    , decltype(_impl_.user_id_){0u}
  };
}

RelationInfoBase::~RelationInfoBase() {
  // @@protoc_insertion_point(destructor:raybo.RelationInfoBase)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RelationInfoBase::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.friend_list_.~RepeatedField();
  _impl_.black_list_.~RepeatedField();
}

void RelationInfoBase::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RelationInfoBase::Clear() {
// @@protoc_insertion_point(message_clear_start:raybo.RelationInfoBase)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.friend_list_.Clear();
  _impl_.black_list_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.ver_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.user_id_) -
        reinterpret_cast<char*>(&_impl_.ver_)) + sizeof(_impl_.user_id_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RelationInfoBase::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 ver = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_ver(&has_bits);
          _impl_.ver_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 user_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_user_id(&has_bits);
          _impl_.user_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated uint32 friend_list = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_friend_list(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 24) {
          _internal_add_friend_list(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated uint32 black_list = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_black_list(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 32) {
          _internal_add_black_list(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RelationInfoBase::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:raybo.RelationInfoBase)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional uint32 ver = 1;
  if (_internal_has_ver()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_ver(), target);
  }

  // optional uint32 user_id = 2;
  if (_internal_has_user_id()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_user_id(), target);
  }

  // repeated uint32 friend_list = 3;
  {
    int byte_size = _impl_._friend_list_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          3, _internal_friend_list(), byte_size, target);
    }
  }

  // repeated uint32 black_list = 4;
  {
    int byte_size = _impl_._black_list_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          4, _internal_black_list(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:raybo.RelationInfoBase)
  return target;
}

size_t RelationInfoBase::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:raybo.RelationInfoBase)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint32 friend_list = 3;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt32Size(this->_impl_.friend_list_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._friend_list_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated uint32 black_list = 4;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt32Size(this->_impl_.black_list_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._black_list_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional uint32 ver = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_ver());
    }

    // optional uint32 user_id = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_user_id());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RelationInfoBase::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RelationInfoBase::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RelationInfoBase::GetClassData() const { return &_class_data_; }

void RelationInfoBase::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<RelationInfoBase *>(to)->MergeFrom(
      static_cast<const RelationInfoBase &>(from));
}


void RelationInfoBase::MergeFrom(const RelationInfoBase& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:raybo.RelationInfoBase)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _impl_.friend_list_.MergeFrom(from._impl_.friend_list_);
  _impl_.black_list_.MergeFrom(from._impl_.black_list_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.ver_ = from._impl_.ver_;
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.user_id_ = from._impl_.user_id_;
    }
    _impl_._has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RelationInfoBase::CopyFrom(const RelationInfoBase& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:raybo.RelationInfoBase)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RelationInfoBase::IsInitialized() const {
  return true;
}

void RelationInfoBase::InternalSwap(RelationInfoBase* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.friend_list_.InternalSwap(&other->_impl_.friend_list_);
  _impl_.black_list_.InternalSwap(&other->_impl_.black_list_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RelationInfoBase, _impl_.user_id_)
      + sizeof(RelationInfoBase::_impl_.user_id_)
      - PROTOBUF_FIELD_OFFSET(RelationInfoBase, _impl_.ver_)>(
          reinterpret_cast<char*>(&_impl_.ver_),
          reinterpret_cast<char*>(&other->_impl_.ver_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RelationInfoBase::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_relation_5finfo_5fbase_2eproto_getter, &descriptor_table_relation_5finfo_5fbase_2eproto_once,
      file_level_metadata_relation_5finfo_5fbase_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace raybo
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::raybo::RelationInfoBase*
Arena::CreateMaybeMessage< ::raybo::RelationInfoBase >(Arena* arena) {
  return Arena::CreateMessageInternal< ::raybo::RelationInfoBase >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
